export enum PokeTypesEnum {
    NORMAL = 'normal',
    FIRE = 'fire',
    FIGHTING = 'fighting',
    WATER = 'water',
    FLYING = 'flying',
    GRASS = 'grass',
    POISON = 'poison',
    ELECTRIC = 'electric',
    GROUND = 'ground',
    PSYCHIC = 'psychic',
    ROCK = 'rock',
    ICE = 'ice',
    BUG = 'bug',
    DRAGON = 'dragon',
    GHOST = 'ghost',
    DARK = 'dark',
    STEEL = 'steel',
    FAIRY = 'fairy',
    UNKNOWN = 'unknown',
}